-- Shadow Tyrant - esquema PostgreSQL para Supabase.
-- Execute este arquivo no SQL Editor de um projeto Supabase novo.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    name text not null default 'Jogador',
    profile_image_url text,
    title text not null default 'Cacador das Sombras',
    account_level integer not null default 1 check (account_level > 0),
    xp integer not null default 0 check (xp >= 0),
    xp_next integer not null default 100 check (xp_next > 0),
    coins integer not null default 0 check (coins >= 0),
    rubies integer not null default 0 check (rubies >= 0),
    last_login timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.characters (
    id bigint generated by default as identity primary key,
    name text not null,
    class_name text not null,
    description text,
    image_url text,
    rarity text not null default 'comum',
    enabled boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.player_characters (
    id bigint generated by default as identity primary key,
    player_id uuid not null references auth.users(id) on delete cascade,
    character_id bigint not null references public.characters(id) on delete cascade,
    level integer not null default 1 check (level > 0),
    xp integer not null default 0 check (xp >= 0),
    xp_next integer not null default 100 check (xp_next > 0),
    active boolean not null default false,
    unlocked_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (player_id, character_id)
);

create unique index if not exists one_active_character_per_player
    on public.player_characters(player_id)
    where active;

create table if not exists public.event_progress (
    id bigint generated by default as identity primary key,
    player_id uuid not null references auth.users(id) on delete cascade,
    event_code text not null default 'lua_sangrenta',
    enemies_killed integer not null default 0 check (enemies_killed >= 0),
    dungeons_completed integer not null default 0 check (dungeons_completed >= 0),
    potions_used integer not null default 0 check (potions_used >= 0),
    bosses_defeated integer not null default 0 check (bosses_defeated >= 0),
    event_missions_completed integer not null default 0 check (event_missions_completed >= 0),
    claimed_track_reward integer not null default 0 check (claimed_track_reward >= 0),
    updated_at timestamptz not null default now(),
    unique (player_id, event_code)
);

create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    summary text not null,
    image_url text,
    link_url text,
    enabled boolean not null default true,
    published_at timestamptz not null default now()
);

insert into public.characters
    (id, name, class_name, description, image_url, rarity, enabled)
values
    (1, 'Sunless', 'Cacador das Sombras',
     'Slayer equilibrado para combate corpo a corpo e esquiva rapida.',
     'assets/images/personagens/sunless-padrao-corrigido.png', 'lendario', true)
on conflict (id) do update set
    name = excluded.name,
    class_name = excluded.class_name,
    description = excluded.description,
    image_url = excluded.image_url,
    rarity = excluded.rarity,
    enabled = excluded.enabled;

select setval(
    pg_get_serial_sequence('public.characters', 'id'),
    greatest((select coalesce(max(id), 1) from public.characters), 1)
);

insert into public.news (id, title, summary, link_url)
values (1, 'Evento: Lua Sangrenta', 'Novos desafios e recompensas exclusivas!', 'evento.html')
on conflict (id) do update set
    title = excluded.title,
    summary = excluded.summary,
    link_url = excluded.link_url;

select setval(
    pg_get_serial_sequence('public.news', 'id'),
    greatest((select coalesce(max(id), 1) from public.news), 1)
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists player_characters_touch_updated_at on public.player_characters;
create trigger player_characters_touch_updated_at
before update on public.player_characters
for each row execute function public.touch_updated_at();

drop trigger if exists event_progress_touch_updated_at on public.event_progress;
create trigger event_progress_touch_updated_at
before update on public.event_progress
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, name)
    values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), 'Jogador'));

    insert into public.player_characters (player_id, character_id, active)
    values (new.id, 1, true);

    insert into public.event_progress (player_id, event_code)
    values (new.id, 'lua_sangrenta');

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.select_character(selected_character_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null then
        raise exception 'Autenticacao obrigatoria';
    end if;

    if not exists (
        select 1
        from public.player_characters
        where player_id = auth.uid() and character_id = selected_character_id
    ) then
        raise exception 'Personagem indisponivel';
    end if;

    update public.player_characters
    set active = (character_id = selected_character_id)
    where player_id = auth.uid();
end;
$$;

create or replace function public.complete_match(
    target_player_id uuid,
    enemies_gained integer,
    dungeons_gained integer,
    coins_gained integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    progress_row public.event_progress;
begin
    insert into public.event_progress (player_id, event_code)
    values (target_player_id, 'lua_sangrenta')
    on conflict (player_id, event_code) do nothing;

    update public.event_progress
    set enemies_killed = enemies_killed + greatest(enemies_gained, 0),
        dungeons_completed = dungeons_completed + greatest(dungeons_gained, 0)
    where player_id = target_player_id and event_code = 'lua_sangrenta'
    returning * into progress_row;

    update public.profiles
    set coins = coins + greatest(coins_gained, 0),
        last_login = now()
    where id = target_player_id;

    return to_jsonb(progress_row);
end;
$$;

revoke all on function public.complete_match(uuid, integer, integer, integer) from public;
grant execute on function public.complete_match(uuid, integer, integer, integer) to service_role;
grant execute on function public.select_character(bigint) to authenticated;

alter table public.profiles enable row level security;
alter table public.characters enable row level security;
alter table public.player_characters enable row level security;
alter table public.event_progress enable row level security;
alter table public.news enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

revoke update on public.profiles from authenticated;
grant update (name, profile_image_url) on public.profiles to authenticated;

drop policy if exists "characters_read" on public.characters;
create policy "characters_read"
on public.characters for select
to authenticated
using (enabled);

drop policy if exists "player_characters_read_own" on public.player_characters;
create policy "player_characters_read_own"
on public.player_characters for select
to authenticated
using (player_id = auth.uid());

drop policy if exists "event_progress_read_own" on public.event_progress;
create policy "event_progress_read_own"
on public.event_progress for select
to authenticated
using (player_id = auth.uid());

drop policy if exists "news_read" on public.news;
create policy "news_read"
on public.news for select
to authenticated
using (enabled);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'profiles',
    'profiles',
    true,
    8388608,
    array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "profile_images_select" on storage.objects;
create policy "profile_images_select"
on storage.objects for select
to public
using (bucket_id = 'profiles');

drop policy if exists "profile_images_insert_own" on storage.objects;
create policy "profile_images_insert_own"
on storage.objects for insert
to authenticated
with check (
    bucket_id = 'profiles'
    and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "profile_images_update_own" on storage.objects;
create policy "profile_images_update_own"
on storage.objects for update
to authenticated
using (
    bucket_id = 'profiles'
    and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
    bucket_id = 'profiles'
    and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "profile_images_delete_own" on storage.objects;
create policy "profile_images_delete_own"
on storage.objects for delete
to authenticated
using (
    bucket_id = 'profiles'
    and (storage.foldername(name))[1] = auth.uid()::text
);
